services:
  wiki:
    image: nginx:alpine
    container_name: wiki
    ports:
      - "8081:80"
    volumes:
      - /opt/sites/wiki.gsblocal7.b/public/wiki.gsblocal7/:/var/www/html
      - /opt/sites/wiki.gsblocal7.b/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: wiki-php-fpm
    volumes:
      - /opt/sites/wiki.gsblocal7.b/public/wiki.gsblocal7/:/var/www/html
